<a href="https://colab.research.google.com/github/Codetemped/project_mern_memories/blob/PART_1_and_2/iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reading file from system

In [1]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving iris Csv.csv to iris Csv.csv
User uploaded file "iris Csv.csv" with length 4551 bytes


Importing necessory libraries

In [2]:
import pandas as pd
import io
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense


In [4]:
dataset=pd.read_csv('iris Csv.csv')

In [24]:
dataset.head(10)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
7  4.4  2.9  1.4  0.2  Iris-setosa
8  4.9  3.1  1.5  0.1  Iris-setosa
9  5.4  3.7  1.5  0.2  Iris-setosa

In [35]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y1=encoder.fit_transform(y)
y=pd.get_dummies(y1).values

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

Training and compiling the model

In [36]:

model=Sequential()
model.add(Dense(4,input_shape=(4,),activation='relu'))
model.add(Dense(3,activation='softmax'))

model.compile(
    optimizer='Adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
model.fit(x_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
12/12 [==============================] - 1s 2ms/step - loss: 2.3705 - accuracy: 0.3361
Epoch 2/100
12/12 [==============================] - 0s 1ms/step - loss: 1.9734 - accuracy: 0.3361
Epoch 3/100
12/12 [==============================] - 0s 2ms/step - loss: 1.5778 - accuracy: 0.3445
Epoch 4/100
12/12 [==============================] - 0s 2ms/step - loss: 1.2595 - accuracy: 0.3782
Epoch 5/100
12/12 [==============================] - 0s 1ms/step - loss: 1.0587 - accuracy: 0.4370
Epoch 6/100
12/12 [==============================] - 0s 1ms/step - loss: 0.9986 - accuracy: 0.4454
Epoch 7/100
12/12 [==============================] - 0s 1ms/step - loss: 0.9704 - accuracy: 0.5714
Epoch 8/100
12/12 [==============================] - 0s 2ms/step - loss: 0.9570 - accuracy: 0.5882
Epoch 9/100
12/12 [==============================] - 0s 1ms/step - loss: 0.9404 - accuracy: 0.6134
Epoch 10/100
12/12 [==============================] - 0s 2ms/step - loss: 0.9281 - accuracy: 0.6387
Epoch 11/

In [38]:
y_pred=model.predict(x_test)
y_test_class=np.argmax(y_test,axis=1)
y_pred_class=np.argmax(y_pred,axis=1)

1/1 [==============================] - 0s 58ms/step


In [40]:
from sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         8

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]]
